### ISSUE TITLE
⚓️ Elasticsearch Hook: Configuration of index suffix date pattern

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#130]
As a SCB User i would like to configure the elasticsearch index pattern more precisely when i install the elasticsearch persistence hook. This feature will be useful to optimize the elasticsearch result index size, rollover strategie and performance.

As for now it is already possible to configure the *index prefix* via the helm chart config:
```yaml
# Define a specific index prefix
indexPrefix: "scbv2" 
```

Additionally it should be possible to configure a date pattern as *suffix* to change the index aggregation level:

```yaml
# Define a specific index prefix
indexPrefix: "scbv2"
# Define a specific index suffix based on date pattern (YEAR, MONTH, WEEK, DATE)
indexSuffix: “YYYY-MM-DD”
# Define if the name of the namespace where this hook is deployed to must be added to the index name. The namespace can be used to separate index by tenants (namespaces).
indexAppendNamespace: true
```

### Examples
Example index names that should be possible to configure:

- `scbv2-team-2020-10-05` (daily rollover pattern, append namespace: true)
- `scbv2-team-2020-10` (monthly rollover pattern, append namespace: true)
- `scbv2-team-2020` (yearly rollover pattern, append namespace: true)
- `scbv2-team-2020-45` (weekly rollover pattern, append namespace: true)
- `scbv2-team` (no rollover pattern, append namespace: true)

- `scbv2-2020-10-05` (daily rollover pattern, append namespace: false)
- `scbv2-2020-10` (monthly rollover pattern, append namespace: false)
- `scbv2-2020` (yearly rollover pattern, append namespace: false)
- `scbv2-2020-45` (weekly rollover pattern, append namespace: false)
- `scbv2` (no rollover pattern, append namespace: false)

### Where to start?
As a starting point here a pointer to the current implementation:

https://github.com/secureCodeBox/secureCodeBox-v2/blob/25b548d47795dba2891f45c7d11381ab69275ac5/hooks/persistence-elastic/hook.js#L50

### Todos:
- [ ]  Update HelmChart config defaults
- [ ]  Implement feature within hook.js
- [ ]  Add additional unit tests for the different configuration options/combinations.

**Comment by J12934** [comment]
Hi @sufisaid 👋,
are you currently working on this?
Otherwise we'd plan to do this in out coming spring (next 2 weeks).

**Comment by sufisaid** [comment]
Hello @J12934 
Sorry to you and the team. I was so busy that I didn't find time for this one. I had best intention.
