### ISSUE TITLE
Epic: Maintenance and Improvements For Release v3.X

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#293]
With the next major release version v3.0.0 of the *secureCodeBox* we want to apply some improvements and maintenance in our Repository. This issue should list all Major (breaking) changes due to maintenance.

### Cascading Scans

The current image name for the cascading scans as well as the directory name where its helm
chart _"declarative-subsequent-scans"_ is located is not quite precise and could be miss leading.
To resolve this we want to change the name for directory and docker images to `cascading-scans`

**This change will also impact the name of the helm chart and is therefore breaking.**

### MS Teams Webhook

We plan to generalize this Hook to Notify other providers as well.
The name of this hook will have to change.

**This change will also impact the name of the helm chart and is therefore breaking.**

# Todo:
- [x] Name Consistency In Docker Images #471
- [x] Refactor Consistency in HelmChart Values #472
- [x] Renaming Hooks: Cascading Scans
- [x] Remove naming inconsistencies (podAnnotations) in http-webhook demo-app. See #467
- [x] Remove the Slack Hook folder #524 
- [x] Add a teams notifier to the notification hook #318
- [x] Update Operator to use Kubebuilder v3 #399
- [x] Refactor / rename the demo-apps folder to demo-targets #507
- [x] Rename `lurcher` to `lurker` #535
- [x] Validate Findings in Unit Tests #520 
- [x] Change OSI Layer to TCP/IP Model Layer or remove it from the docs #543   
- [x] Versionierung der Doku klären secureCodeBox/documentation#93
- [x] Findings Format: Name, Severity and Category set to required #557
- [x] Remove Teams Hook https://github.com/secureCodeBox/secureCodeBox/issues/545 
- [x] DefectDojo Hook syncFindingsBackMode auf v3 Findingsformat anpassen.

**Comment by J12934** [comment]
Also potentially braking as this migrates out CRDs to the new version `apiextensions.k8s.io/v1` (from `apiextensions.k8s.io/v1beta1`), see issue #399.

We should perform this change before the kubernetes 1.22 release which should happen around august 21, best if we can do our release a bit earlier to give people some time to update their scb opeator before they update their kubernetes version.

We might be able to make some changes to make these changes so that it avoid most scenarios where this could cause problems, but would probably still be best to do it in a major release to be sure.

**Comment by JohannesZahn** [comment]
Please add #543 to the list
