### ISSUE TITLE
Improve Findings Format

### ISSUE THREAD

**Issue by JohannesZahn** [secureCodeBox/secureCodeBox#519]
The [Findings Format](https://docs.securecodebox.io/docs/api/finding) is used e.g. to export data to other Applications like DefectDojo, however some necessary and/or useful information is not included in the Findings. 

Therefore we will collect a List of possible Improvements here. We are happy about any suggestions by the community.

# Release 4.0 Scope
- [x] Add Timestamp of when a Finding was identified (called `identified_at`), it should be optional as we do not always have this exact information. #1434

- [X] Add Timestamp of when a Finding was parsed (called `parsed_at`) as a fallback when `identified_at` is not present. Will be solved by #492 
- [ ] Add additional JSON attributes, that give information about how a Finding was identified ("evidence", "steps_to_reproduce"?) or what impact it has ("impact"?), see **https://github.com/secureCodeBox/secureCodeBox/issues/332#issuecomment-835778057** @secureCodeBox/contributer-team do we have any data available to do this?
- [x] Add optional JSON attribute "mitigation" for solutions how the vulnerability might be fixed, can be populated i.e. by "zap_solution" in zap  https://github.com/secureCodeBox/secureCodeBox/pull/1639
- [x]  Make severity, category and name required **breaking** => update findings format check 
- [ ] Add optional JSON attribute "cve" for CVEas present i.e. in trivy https://github.com/secureCodeBox/secureCodeBox/pull/1676
- [ ] Add optional JSON attribute "cwe" for CWE as present i.e. in ZAP https://github.com/secureCodeBox/secureCodeBox/pull/1676
- [ ] Add optional JSON attribute "notes"/"other"/"additional_info" for other important information text that clarifies the vulnerability. 

# Additional Ideas for further development
- [ ] Add optional JSON attribute "vulnerability_id_from_tool" for ids of vulnerabilities assigned by the specific scanners

@secureCodeBox/contributer-team please share any ideas you have in the comments.

**Comment by JohannesZahn** [comment]
@damiencarol when you were talking about the Request/Answer Part [here](https://github.com/secureCodeBox/secureCodeBox/issues/332#issuecomment-835778057), do those resemble the mitigation and impact fields in your Findings format or what other fields would be populated with this information?

**Comment by JohannesZahn** [comment]
Some Scanners like nikto seem to supply vulnerability IDs like in the following examle. Could this be useful information for the "vulnerability_id_from_tool" field in DefectDojo @damiencarol?

```json
[
  {
    "id":"999996",
    "OSVDB":"0",
    "method":"GET",
    "url":"/robots.txt",
    "msg":"\"robots.txt\" contains 1 entry which should be manually viewed."
  },
  {
    "id":"740001",
    "OSVDB":"0",
    "method":"HEAD",
    "url":"/10.96.193.17.zip",
    "msg":"Potentially interesting backup/cert file found. "
  },
  {
    "id":"740001",
    "OSVDB":"0",
    "method":"HEAD",
    "url":"/backup.tar",
    "msg":"Potentially interesting backup/cert file found. "
  }
]
```

**Comment by rseedorff** [comment]
Relates also to #322

**Comment by damiencarol** [comment]
1. "Request/Answer Part" means the HTTP requests/answer that the pen-test tools record during a scan. We have data structure to support that and a UI to show them
2. "vulnerability_id_from_tool" => it depends. Basically we have 2 attributes:
   - `vuln_id_from_tool` , could be a rule, a check name, a kind a vulnerability,... by it's not unique, you can have it multiple time for one tool. For ex for Bandit: `B105  hardcoded_password_string`
   - `unique_id_from_tool` is really unique. For ex it could be a GUID from an API.
