### ISSUE TITLE
🏗 [Epic] Ensure Test Pipeline runs Correctly on Forks

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#612]
Depends on #611 

- [x] Export build Operator and Parser & Hook SDK as `.tar` and save them as pipeline artifacts
- [x] Import Operator and SDK in depended scanner and hook jobs
- [x] Ensure that our GitHub Pipeline is using the new makefile commands for `scanner` and `hooks`
- [x] Add PR trigger to primary pipeline

**Comment by fuhrmeistery** [comment]
Can you elaborate what you mean with 'Add PR trigger to primary pipeline'?

**Comment by J12934** [comment]
@fuhrmeistery The on push trigger to the primary pipeline needs to be extended so that the pipeline ist actually triggered by pull requests and not just on push.

**Comment by Ilyesbdlala** [comment]
Done. PoC: https://github.com/secureCodeBox/secureCodeBox/pull/1124
