### ISSUE TITLE
:construction:  [Consistency] Ensuring file/code consistency for scanners

### ISSUE THREAD

**Issue by SebieF** [secureCodeBox/secureCodeBox#620]
As a secureCodeBox developer and maintainer I would like to have consistency between all provided resources, especially scanners. This should speed up the development process, enable a consistent documentation and make maintenance simpler.

Consistency can be achieved manually by aligning all existing files manually, I think the best and most sustainable way would be to have tests (in the ci pipeline), that point out on inconsistent file and coding standards.

Files that should be considered for scanners:
- [x] **Chart.yaml** (#685)
- [x] **values.yaml** (#693)
- [x] templates/**cascading-rules.yaml** (#691)
- [x] templates/scanner-name-**parse-definition.yaml**
- [x] templates/scanner-name-**scan-type.yaml** (#689)
- [x] *parser*: All parsers should be tested for an empty / erroring result file (#701)
- [x] *parser*: All parsers should have the same output standard for findings (see #619)

Ensuring consistency in the future:
- [x] Create template files and a make command to automatically create a new scanner directory with consistent files (#684)
- [x] Change documentation where necessary
