### ISSUE TITLE
[Epic] CI Migration To use Makefile Builds

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#717]
Acceptance Criteria:

- CICD Pipeline Build for all Scanner, Hooks and integration-tests are based on makefile targets

Long Read:

A while ago, we introduced Makefiles to simplify the process of building and testing for all of our project components.
These Makefiles were also required to redesign the CI workflow in a maintainable way and to get rid of all the unnecessary pushes to DockerHub on every push. 

For migrating scanners, there is already a new job introduced in the ci.yaml containing most of the scanners in PR #712.

To finish the migration, the following steps need to be done:
- [x] Migrate git-repo-scanner (PR #712)
- [x] https://github.com/secureCodeBox/secureCodeBox/issues/963
- [x] https://github.com/secureCodeBox/secureCodeBox/issues/964
- [x] https://github.com/secureCodeBox/secureCodeBox/issues/965

Cleanup afterwards:
- [x] Remove 'integration-tests' job
- [x] Remove 'Unit-Tests | JavaScript' job
- [x] Remove 'Unit-Tests | Python' job
- [x] Add demo-targets build to release-build.yaml #1062 
- [ ] Cache Images for demo-targets

**Comment by malexmave** [comment]
This should also resolve #940 (duplication of `integration-tests` target). See [discussion in #712](https://github.com/secureCodeBox/secureCodeBox/pull/712#issuecomment-938607194) for what the reason for the duplication was, and what the goal state would be.

Thanks @EndPositive for pointing this out :).

**Comment by rseedorff** [comment]
Everything seems to be fixed. Not sure if the last aspect `Cache Images for demo-targets` is relevant any more 🤔
If so, we could raise a new issue for that later on.
